models:
  - name: "Groq Llama 3.3 70B"
    provider: groq
    model: llama-3.3-70b-versatile
    apiKey: gsk_ebUXvGygijGqUtcj909WGdyb3FYVWXH4h18mc3HgE8BJ0Sgi9jE
  - name: "Groq Llama 3.1 8B"
    provider: groq
    model: llama-3.1-8b-instant
    apiKey: gsk_ebUXvGygijGqUtcj909WGdyb3FYVWXH4h18mc3HgE8BJ0Sgi9jE